theme: jekyll-theme-cayman
title: "Informed Scientific Sampling in Large-scale Outdoor Environments"
tagline: "November 8 in Room LG-R20"
tagline: "@IROS 2019 Macau"
github:
  is_project_page: false
kramdown:
    auto_ids: true
