theme: jekyll-theme-cayman
title: "Tentative: Informed Scientific Sampling in Large-scale Outdoor Environments"
tagline: "@IROS 2019 Macau"
github:
  is_project_page: false
kramdown:
    auto_ids: true
